# Generated by Django 6.0.3 on 2026-04-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tierce',
            fields=[
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('id_tierce', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('type_Tierce', models.CharField(choices=[('etudiant', 'etudiant'), ('professeur', 'professeur')], default='etudiant', max_length=30)),
            ],
        ),
    ]
