# Generated by Django 6.0.3 on 2026-04-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_materiel', models.IntegerField()),
                ('couleur', models.CharField(max_length=20)),
                ('Marque', models.CharField(max_length=20)),
                ('etat', models.CharField(choices=[('disponible', 'disponible'), ('En pret', 'En pret'), ('Defectueux', 'Defectueux'), ('Hors service', 'Hors service')], default='disponible', max_length=30)),
            ],
        ),
    ]
