# Generated by Django 6.0.3 on 2026-04-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_materiel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='id_materiel',
        ),
    ]
