# Generated by Django 6.0.4 on 2026-05-04 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_tierce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tierce',
        ),
    ]
