# Generated by Django 6.0.3 on 2026-05-24 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('nombre_places', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id_materiel', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=30)),
                ('numero_serie', models.CharField(max_length=30)),
                ('categorie', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('AUDIOVISUEL', 'Audiovisuel'), ('MOBILIER', 'Mobilier'), ('RESEAU', 'Réseau & Télécommunications'), ('LABORATOIRE', 'Laboratoire'), ('SPORT', 'Sport'), ('BUREAUTIQUE', 'Bureautique'), ('SECURITE', 'Sécurité'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie')),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN PRET', 'En prêt'), ('DEFECTUEUX', 'Defectueux'), ('EN MAINTENANCE', 'En maintenance'), ('HORS SERVICE', 'Hors service')], default='DISPONIBLE', max_length=14, verbose_name='État')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('type_operation', models.CharField(choices=[('entree', 'Entrée (enregistrement)'), ('sortie', 'Sortie (planifiée)'), ('emprunt', 'Emprunt')], default='emprunt', max_length=30, verbose_name="Type d'opération")),
                ('materiels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='equipement.materiel')),
            ],
        ),
        migrations.CreateModel(
            name='Tierce',
            fields=[
                ('id_Tierce', models.CharField(db_column='id_tierce', max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('type_Tierce', models.CharField(choices=[('etudiant', 'etudiant'), ('professeur', 'professeur')], default='etudiant', max_length=30, verbose_name='Type')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipement.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='equipement.operation')),
                ('date_retour_prevue', models.DateField(blank=True, null=True)),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('retourne', 'Retourné')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.classe')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.tierce')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-date_operation'],
            },
            bases=('equipement.operation',),
        ),
        migrations.CreateModel(
            name='LigneEmprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_emprunt', to='equipement.materiel', verbose_name='Matériel')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipement.emprunt', verbose_name='Emprunt')),
            ],
            options={
                'unique_together': {('emprunt', 'materiel')},
            },
        ),
    ]
