# Generated by Django 6.0.3 on 2026-04-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id_materiel', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=30)),
                ('categorie', models.CharField(max_length=50)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN PRET', 'En prêt'), ('DEFECTUEUX', 'Defectueux'), ('EN MAINTENANCE', 'En maintenance'), ('HORS SERVICE', 'Hors service')], default='DISPONIBLE', max_length=14, verbose_name='État')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
    ]
