# Generated by Django 6.0.3 on 2026-05-08 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id_materiel', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=30)),
                ('categorie', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('AUDIOVISUEL', 'Audiovisuel'), ('MOBILIER', 'Mobilier'), ('RESEAU', 'Réseau & Télécommunications'), ('LABORATOIRE', 'Laboratoire'), ('SPORT', 'Sport'), ('BUREAUTIQUE', 'Bureautique'), ('SECURITE', 'Sécurité'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie')),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN PRET', 'En prêt'), ('DEFECTUEUX', 'Defectueux'), ('EN MAINTENANCE', 'En maintenance'), ('HORS SERVICE', 'Hors service')], default='DISPONIBLE', max_length=14, verbose_name='État')),
                ('marque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tierce',
            fields=[
                ('id_Tierce', models.CharField(db_column='id_tierce', max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('type_Tierce', models.CharField(choices=[('etudiant', 'etudiant'), ('professeur', 'professeur')], default='etudiant', max_length=30, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField(verbose_name='Retour prévu')),
                ('date_retour_effective', models.DateField(blank=True, null=True, verbose_name='Retour effectif')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('EN_ATTENTE', 'En attente')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='equipement.materiel', verbose_name='Matériel')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='equipement.tierce', verbose_name='Emprunteur')),
            ],
        ),
        migrations.CreateModel(
            name='LigneEmprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipement.emprunt', verbose_name='Emprunt')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_emprunt', to='equipement.materiel', verbose_name='Matériel')),
            ],
            options={
                'unique_together': {('emprunt', 'materiel')},
            },
        ),
    ]
