# Generated by Django 6.0.3 on 2026-04-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('nom', models.CharField(max_length=200)),
                ('libelle', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=400)),
                ('id_categorie', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant')),
            ],
        ),
    ]
