# Generated by Django 6.0.3 on 2026-05-15 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('nombre_places', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='emprunt',
            options={'ordering': ['-date_emprunt'], 'verbose_name': 'Emprunt', 'verbose_name_plural': 'Emprunts'},
        ),
        migrations.RemoveField(
            model_name='emprunt',
            name='date_retour_effective',
        ),
        migrations.AddField(
            model_name='emprunt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprunt',
            name='date_retour_reelle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='type_operation',
            field=models.CharField(choices=[('entree', 'Entrée (enregistrement)'), ('sortie', 'Sortie (planifiée)'), ('emprunt', 'Emprunt')], default='emprunt', max_length=20),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_retour_prevue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='emprunteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipement.tierce'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='materiel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='equipement.materiel'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('retourne', 'Retourné')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipement.classe'),
        ),
    ]
