# Generated by Django 6.0.2 on 2026-05-20 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_classe_alter_emprunt_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tierce',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='equipement.classe'),
        ),
    ]
