# Generated by Django 5.2.14 on 2026-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0002_alter_classe_id_alter_emprunt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rappel',
            name='type_rappel',
            field=models.CharField(choices=[('nouveau_retard', 'Nouveau retard détecté'), ('confirmation_retour', 'Confirmation de retour'), ('retard_1', '1 jour de retard'), ('retard_3', '3 jours de retard'), ('retard_7', '7 jours de retard')], max_length=20, verbose_name='Type de rappel'),
        ),
    ]
