# Generated by Django 6.0.4 on 2026-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0003_tierce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.AlterField(
            model_name='tierce',
            name='id_tierce',
            field=models.CharField(db_column='id_tierce', max_length=50, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
        migrations.RenameField(
            model_name='tierce',
            old_name='id_tierce',
            new_name='id_Tierce',
        ),
    ]
