# Generated by Django 6.0.3 on 2026-05-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0004_delete_categorie_alter_tierce_id_tierce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField(verbose_name='Retour prévu')),
                ('date_retour_effective', models.DateField(blank=True, null=True, verbose_name='Retour effectif')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('RETOURNE', 'Retourné'), ('EN_RETARD', 'En retard'), ('EN_ATTENTE', 'En attente')], default='EN_COURS', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='equipement.tierce', verbose_name='Emprunteur')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='equipement.materiel', verbose_name='Matériel')),
            ],
        ),
    ]
