# Generated by Django 6.0.3 on 2026-05-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipement', '0005_emprunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='categorie',
            field=models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('AUDIOVISUEL', 'Audiovisuel'), ('MOBILIER', 'Mobilier'), ('RESEAU', 'Réseau & Télécommunications'), ('LABORATOIRE', 'Laboratoire'), ('SPORT', 'Sport'), ('BUREAUTIQUE', 'Bureautique'), ('SECURITE', 'Sécurité'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='LigneEmprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emprunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='equipement.emprunt', verbose_name='Emprunt')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_emprunt', to='equipement.materiel', verbose_name='Matériel')),
            ],
            options={
                'unique_together': {('emprunt', 'materiel')},
            },
        ),
    ]
