# Generated by Django 6.0.3 on 2026-05-18 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipement', '0002_classe_alter_emprunt_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inventaire', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaires', to='equipement.classe')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventaire',
                'verbose_name_plural': 'Inventaires',
                'ordering': ['-date_inventaire'],
                'unique_together': {('classe', 'date_inventaire')},
            },
        ),
        migrations.CreateModel(
            name='LigneInventaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_initial', models.IntegerField(help_text='Stock initial dans la classe')),
                ('stock_emprute', models.IntegerField(default=0, help_text="Nombre d'équipements empruntés")),
                ('stock_reel', models.IntegerField(help_text="Nombre d'équipements réellement présents")),
                ('difference', models.IntegerField(editable=False, help_text='Différence entre stock initial et stock réel')),
                ('inventaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='inventaire.inventaire')),
            ],
            options={
                'verbose_name': "Ligne d'inventaire",
                'verbose_name_plural': "Lignes d'inventaire",
            },
        ),
    ]
